### ISSUE TITLE
Support for teensy 3.1 and 3.2

### ISSUE THREAD

**Issue by larsvankleef** [tsandmann/freertos-teensy#10]
Would it be possible to make this library work on a teensy 3.1 or 3.2? Or are there limitations on this board that would keep this from working?

**Comment by tsandmann** [comment]
This library uses the ARM_CM4F (Cortex-M4F) port of the FreeRTOS kernel. The teensy 3.1/3.2 boards use a Cortex-M4 controller (without FPU), so for these boards the ARM_CM3 port (Cortex-M3/4) would be needed instead. Maybe it's possible to create a combined library, but I haven't checked that.
