### ISSUE TITLE
Teensy.h

### ISSUE THREAD

**Issue by FalseViking** [tsandmann/freertos-teensy#16]
Hello there.

I am, whenever using the #include <freertos_arduino.h>, getting the follow error:
Arduino\libraries\freertos-teensy\src/arduino_freertos.h:222:0,
sketch_mar28a.ino:26: (Note, the mistake is at whatever line the first command is called)
\Arduino\libraries\freertos-teensy\src/portable/teensy.h:138:40: error: 'offset_' declared as an 'inline' field
static inline timeval offset_ {0, 0};
                                               ^
arning: 'constexpr' needed for in-class initialization of static data member 'timeval freertos::clock::offset_' of non-integral type [-fpermissive]
This error code comes from the main.ccp. In my own sketch, I get the issue at line 1, as the #include is at line 1.

If I comment out the freertos_arduino, from my code, looking like this:
`#include <arduino_freertos.h>
#include <FreeRTOS.h>
#include <task.h>
#include <queue.h>

#define sample_rate_hz 80000
#define sample_period (10000000/sample_rate_hz)
#define buffer_size 1024

const int analogPin = A0;
uint16_t buffer[buffer_size];
uint16_t buffer_index = 0;
QueueHandle_t adc_queue;

void setup(){

}

void loop(){
    
}`

The error code I get then:

In file included from c:\Users\soren\OneDrive\Documents\Arduino\libraries\freertos-teensy\src\portable\event_responder_support.cpp:27:0:
c:\Users\soren\OneDrive\Documents\Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: error: 'offset_' declared as an 'inline' field
     static inline timeval offset_ {0, 0};
                                                    ^
Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: warning: 'constexpr' needed for in-class initialization of static data member 'timeval freertos::clock::offset_' of non-integral type [-fpermissive]
In file included from Arduino\libraries\freertos-teensy\src\portable\teensy_4.cpp:32:0:
Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: error: 'offset_' declared as an 'inline' field
     static inline timeval offset_ {0, 0};
                                                    ^
Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: warning: 'constexpr' needed for in-class initialization of static data member 'timeval freertos::clock::offset_' of non-integral type [-fpermissive]
In file included from Arduino\libraries\freertos-teensy\src\portable\teensy_common.cpp:39:0:
Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: error: 'offset_' declared as an 'inline' field
     static inline timeval offset_ {0, 0};
                                                    ^
Arduino\libraries\freertos-teensy\src\portable\teensy.h:138:40: warning: 'constexpr' needed for in-class initialization of static data member 'timeval freertos::clock::offset_' of non-integral type [-fpermissive]

While the program is short and not saying much, I've been busy trying to troubleshoot the teensy.h issue, without any results, before continuing. 

Any help is appreciated.

**Comment by tsandmann** [comment]
This should be fixed with the latest release now.
