### ISSUE TITLE
PlatformIO: Can't find 'arduino_freertos.h' when using strict library compatibility mode

### ISSUE THREAD

**Issue by pharapeti** [tsandmann/freertos-teensy#17]
**Problem**
When the following property is specified:
`lib_compat_mode = strict`

The PlatformIO library dependency resolved is unable to find the base 'arduino_freertos.h' header file.
`src/main.cpp:2:12: fatal error: arduino_freertos.h: No such file or directory`

**Steps to reproduce:**
1. Open blink example within examples/blink
2. Specify strict library compatibility mode within the platformio.ini file (ex: under teensy4.0)
3. Try to build project and expect to see same error as above

**Potential Solutions**
I suspect the file structure used in this repo does not follow the typical 'PlatformIO library' directory structure. As such, P.IO struggles to identify the header file.

This may also be fixed by using an appropriate [P.IO library dependency finder mode](https://docs.platformio.org/en/latest/librarymanager/ldf.html#dependency-finder-mode) - however I haven't tested this fully.

**Comment by tsandmann** [comment]
Should be fixed now, thanks for reporting this.
