### ISSUE TITLE
Add option to sponsor the project

### ISSUE THREAD

**Issue by heidtn** [tsandmann/freertos-teensy#26]
This is more of a thank you than anything, but I've been wanting this port for the teensy for many years.  If you were to add a [sponsor button](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository) I know I and perhaps others would contribute if that was something you were interested in.

Otherwise happy to contribute upstream as we uncover new issues.  And great work on the build!  I just ported an existing project >10kloc in about 20 minutes with minimal effort.  Thank you for making this available to the community!

**Comment by tsandmann** [comment]
Thank you! There are currently no plans to add sponsoring, but I'll think about it.
