### ISSUE TITLE
Teensy FreeRTOS EventResponder

### ISSUE THREAD

**Issue by Stevenlawrencehoriba** [tsandmann/freertos-teensy#30]
Further to recetn issues reported and problems with all these lib updates.. We use the QNEthernet library, and since all the updates, adding in this library fails the system to run, Although you said you didnt support EventResponder , it was working OK before ALL the updates, So all the updates seem to have changed this.. the comments below are from QNEthernet Author, so calling Yield will be hooked via Event responder, is there any other way, or can you not fix the issues.  For us to manage this we would have to mess around with the libraries and remove dependancy, which negates the use of libraries.

On non-Teensy platforms: Ethernet.loop() must be called regularly, either at the end of the main loop() function, or by hooking into yield(). (This is already done for you on the Teensy platform by hooking into yield() via EventResponder.)

If I removed the Event responder from his Yeidl, or yours, then where is best place to include the loop call? , or is it better for you to fix the issues?

**Comment by tsandmann** [comment]
I can't fix the EventResponder incompatibility, the Teensy core library implements it in a way that makes it incompatible with an RTOS, as written in README.md. 

I don't know anything about the QNEthernet library, but in principle when using an RTOS you call loop functions in their own task that runs periodically. You must, of course, care about the synchronization of all API calls from different tasks, but that's a general point when using a non-threadsafe library with an RTOS.
